DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (	ISBN VARCHAR(32) PRIMARY KEY, 
			TITLE VARCHAR(32), 
			PERSON SERIAL,
			PRICE DECIMAL (6,2));


INSERT INTO BOOKS(ISBN, TITLE, PERSON, PRICE) VALUES('9780671820862', 'Captain America: Holocaust For Hire', 1, 29.90);


