DROP TABLE IF EXISTS BOOKS;


CREATE TABLE AUTHORS (  ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
                        NAME VARCHAR(32) NOT NULL,
                        FAMILY_NAME VARCHAR(32) NOT NULL);


INSERT INTO AUTHORS(NAME, FAMILY_NAME) VALUES('Joseph', 'Silva');


CREATE TABLE BOOKS (	ISBN VARCHAR(32) NOT NULL UNIQUE PRIMARY KEY, 
			TITLE VARCHAR(32) NOT NULL UNIQUE, 
			PERSON INTEGER NOT NULL REFERENCES AUTHORS ON DELETE RESTRICT,
			PRICE DECIMAL (6,2) NOT NULL);


INSERT INTO BOOKS(ISBN, TITLE, PERSON, PRICE) VALUES('9780671820862', 'Captain America: Holocaust For Hire', SELECT ID from AUTHORS WHERE NAME='Joseph' AND FAMILY_NAME='Silva', 29.90);
